spring:
  datasource:
    url: jdbc:h2:./db/devdb;AUTO_SERVER=TRUE;
    driverClassName: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: none
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  resources:
    static-locations:
      - file:./public/
      - file:../jigsawvue/dist/
      - classpath:/META-INF/resources/

logging:
  level:
    com.sds.jigsaw: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
